development:
  adapter: postgresql
  encoding: utf8
  database: ticket_easy_development
  pool: 5
  username: 
  password:
  template: template0

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ticket_easy_test
  pool: 5
  username: 
  password:
  template: template0

cucumber:
  <<: *TEST