# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e94c1da9607f57846eb142ee4f46824d3b155b13e81bdd94340018a64dd181852e88c6c96163b09dac2ed0b680e2d2f3b22434f0beaac4abd055dd364465389f

test:
  secret_key_base: d8e83068c43556d46cad6ff2579ca42ae4ee6a55905c71a8bf656c2ceb939de8df977b230f978f1258c8bde5c4df1e465871ed019364114582a924b6228979f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
